version: '3'

services:
  portainer:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: portainer/portainer
    volumes:
      - ${PORTAINER_DATA_PATH}:/data
      - ${PORTAINER_SSL_PATH}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL:
      SSLCERT: ${PORTAINER_SSL_CERTIFICATE}
      SSLKEY: ${PORTAINER_SSL_KEY}
    command: --admin-password ${ENCRYPTED_PASSWORD}

networks:
    default:
       external:
         name: ${NETWORK}
